name: build docker and publish to orgk

on:
  push:
    branches:
      - 'main'

env:
  GITHUB_ACTOR : ${{github.actor}}
  GITHUB_TOKEN : ${{github.token}}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: generate settings.xml for maven builds
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: >
            [
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/Music-Web-Micro-service/*",
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "true"
                }
              },
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "${GITHUB_ACTOR}",
                "password": "${GITHUB_TOKEN}"
              }
            ]
      -
        name: maven permisson
        run: chmod +x mvnw
      -
        name: maven build up
        run: ./mvnw install package
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{env.REGISTRY}}
          username: ${{env.GITHUB_ACTOR}}
          password: ${{env.GITHUB_TOKEN}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          tags: |
            main
            latest
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
